### ISSUE TITLE
node set to hip on axis software not connecting to slimevr

### ISSUE THREAD

**Issue by GabeVal7** [ButterscotchV/AXSlime#4]
As title says, i drag a node to hip for hip tracking, then when i go to slimevr the node shows up but does not track and eventually disconnects. I tried more than one node to make sure its not just the node and none of them would track.

**Comment by ButterscotchV** [comment]
I believe an update to the AXIS software fixed this behaviour, make sure your AXIS software is up to date.

**Comment by GabeVal7** [comment]
My axis software is on the latest stable version, 0.12.2

**Comment by GabeVal7** [comment]
This turned out to be a error by me, i did not make a steamvr profile in the axis software with the hip tracker enabled and once i did slime vr picked it up.
